### ISSUE TITLE
[Practitioner Guide]: Contributor Sustainability

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-data-science#21]
### Practitioner Guide Topic (1 - 3 words)

Contributor Risk

### Primary Metrics (2 - 4 metrics)

* Bus Factor
* Contributors
* Types of Contributions

### Why is this topic important? How will this help people improve their open source project and / or community? Who will benefit from this guide?

An important consideration for the health of an open source project is whether there are enough contributors to sustain the project. What would happen if one or more contributors suddenly decided to stop working on a project? Could the project continue or would it become unviable? This is an important risk to assess for projects that you are already working on or for projects that you are considering for adoption.

### How would you like to see this guide developed?

I have the experience and time available to write the first draft

### Additional Notes

Here is the doc where this guide will be developed: https://docs.google.com/document/d/1pmsFoQznw-X4mcHZKUwg3a4Npq_OukTHTbh199CnWCk/edit

For an example of a nearly finished Insight Guide that you can use to better understand what should be in each section and how much detail to include, please see the [Responsiveness](https://docs.google.com/document/d/1bRe7m-kIr208H_MaubbU87QIJZJ18wc_g0mN_cEXO_c/edit) guide.

**Comment by cdolfi** [comment]
Not sure what the process would be because these metrics would need to get adopted under CHAOSS (which would like to discuss whether its included in this insights guide or not) but id like to purpose the Heatmap series we have been working on in 8knot as a part of this or maybe another insights, software development or responsiveness maybe. https://eightknot.osci.io/codebase is where it can be found. The heatmaps break down by the directory to have a more granular view on the activity around a repository. The 3 heatmaps: 
- Contributor 
- Contribution
- Reviewer (in final rounds of reviews to be added to the dashboard) 

allow for a view into different parts of the codebase. You can see how long has been the majority reviewers or code contributors have been active to see if the knowledge retention is there, there is a large amount of contributions vs the # of reviewers, etc

**Comment by geekygirldawn** [comment]
I don't think this is a good fit for an insight guide. The insights guides are less about implementation of metrics and more about interpretation of broad concepts - mostly for people who are getting started and struggling to understand how to interpret data about their project, so I'd like to keep the insight guides as simple as possible.

However, I would love to see these implemented as CHAOSS metrics and possibly included into our metrics models, where this would be a great fit. The best way to start that discussion is to attend the next Metrics Development WG meeting on Thursday, Feb 29: https://www.google.com/url?q=https://docs.google.com/document/d/1xsii5tfmmDwWpuhrFcBJMeYeT3RipJdiCdHrbi0NalQ/edit%23heading%3Dh.n3rh3l1y6dv7&sa=D&source=calendar&usd=2&usg=AOvVaw1rDXWuThRGQqMVowYWglAK It might also be good to file it as an issue in that repo to get people thinking about these metrics: https://github.com/chaoss/wg-metrics-development/issues

**Comment by geekygirldawn** [comment]
The [first draft](https://docs.google.com/document/d/1pmsFoQznw-X4mcHZKUwg3a4Npq_OukTHTbh199CnWCk/edit) is now ready for people to review and provide feedback.

**Comment by voongc** [comment]
Here's a case study: https://link.springer.com/chapter/10.1007/978-3-642-33442-9_3
